networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: .  # Set the context to the parent directory (my_project)
      dockerfile: containers/nginx/Dockerfile  # Point to the Dockerfile inside containers/nginx
    ports:
      - "443:443"
      # - "80:80"
    volumes:
      - wordpress_data:/var/www/html  # Persist WordPress data
      # - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx config
      # - ./ssl/cert.pem:/etc/ssl/certs/cert.pem  # SSL cert
      # - ./ssl/my_key.key:/etc/ssl/private/my_key.key  # SSL key
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: .  # Set the context to the parent directory (my_project)
      dockerfile: containers/mariadb/Dockerfile  # Point to the WordPress Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql  # Persist data between container restarts
      - ./containers/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./containers/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"  # Expose port 3306 to the host for MariaDB connections

  wordpress:
    container_name: wordpress
    build:
      context: .  # Set the context to the parent directory (my_project)
      dockerfile: containers/wordpress/Dockerfile  # Point to the WordPress Dockerfile
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    # environment:
    #   WORDPRESS_DB_HOST: mariadb:3306  # Database service to connect to
    #   WORDPRESS_DB_NAME: my_database  # Database name
    #   WORDPRESS_DB_USER: my_user  # Database user
    #   WORDPRESS_DB_PASSWORD: my_password  # Database user password
    volumes:
      - wordpress_data:/var/www/html  # Persist WordPress data
    networks:
      - inception
    depends_on:
      - mariadb  # Ensure MariaDB is up before WordPress
    # entrypoint: ["./wait-for-it.sh", "mariadb:3306", "--", "php-fpm83", "-F"]
    restart: always
    

volumes:
  mariadb_data:  # Declare the named volume for MariaDB data
  wordpress_data:  # Declare the named volume for WordPress data