networks:
  inception:
    name: inception
    # driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: .  # Set the context to the parent directory (my_project)
      dockerfile: containers/nginx/Dockerfile  # Point to the Dockerfile inside containers/nginx
      # image: nginx:42
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - /home/vboxuser/inception/srcs/html:/var/www/html
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: .  # Set the context to the parent directory (my_project)
      dockerfile: containers/mariadb/Dockerfile  # Point to the WordPress Dockerfile    environment:
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Root password for the database
      MYSQL_DATABASE: my_database  # Name of the database to create on startup
      MYSQL_USER: my_user  # Create a user with privileges
      MYSQL_PASSWORD: my_password  # Password for the user
    volumes:
      - mariadb_data:/var/lib/mysql  # Persist data between container restarts
      - ./containers/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql  # Copy init.sql into the container
    networks:
      - inception
    restart: always
    ports:
      - "3306:3306"  # Expose port 3306 to the host for MariaDB connections

  wordpress:
    container_name: wordpress
    build:
      context: .  # Set the context to the parent directory (my_project)
      dockerfile: containers/wordpress/Dockerfile  # Point to the WordPress Dockerfile
    environment:
      WORDPRESS_DB_HOST: mariadb:3306  # Database service to connect to
      WORDPRESS_DB_NAME: my_database  # Database name
      WORDPRESS_DB_USER: my_user  # Database user
      WORDPRESS_DB_PASSWORD: my_password  # Database user password
    volumes:
      - wordpress_data:/var/www/html  # Persist WordPress data
    ports:
      - "8080:80"  # Expose WordPress on port 8080
    networks:
      - inception
    depends_on:
      - mariadb  # Ensure MariaDB is up before WordPress
    restart: always

volumes:
  mariadb_data:  # Declare the named volume for MariaDB data
  wordpress_data:  # Declare the named volume for WordPress data
