networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: .  # Set the context to the parent directory (my_project)
      dockerfile: containers/nginx/Dockerfile  # Point to the Dockerfile inside containers/nginx    image: nginx:42
    ports:
     - "443:443"
    # depends_on:
    #   - wordpress
    # volumes:
    #  - wordpress:/var/www/html
    networks:
      - inception
    # env_file:
    #   - .env
    restart: always