
networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: .  # Set the context to the parent directory (my_project)
      dockerfile: containers/nginx/Dockerfile  # Point to the Dockerfile inside containers/nginx
      # image: nginx:42
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - ./index.html:/var/www/html/index.html  # Mount the local index.html
     - wordpress:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  wordpress: